### ISSUE TITLE
multi-gpu error

### ISSUE THREAD

**Issue by drinkingkazu** [DeepLearnPhysics/lartpc_mlreco3d#11]
Trying to train/inference using multiple gpus fail in a strange way. The issue is identified as running some torch methods before setting device id and os.environ['CUDA_VISIBLE_DEVICES'].

**Comment by drinkingkazu** [comment]
Now there's a legitimate problem at DataParallel.forward
```
Traceback (most recent call last):
  File "bin/run.py", line 29, in <module>
    main()
  File "bin/run.py", line 24, in main
    train(cfg)
  File "/afs/slac.stanford.edu/u/nu/kterao/sw/lartpc_mlreco3d/mlreco/main_funcs.py", line 37, in train
    train_loop(cfg, handlers)
  File "/afs/slac.stanford.edu/u/nu/kterao/sw/lartpc_mlreco3d/mlreco/main_funcs.py", line 235, in train_loop
    res = handlers.trainer.train_step(data_blob)
  File "/afs/slac.stanford.edu/u/nu/kterao/sw/lartpc_mlreco3d/mlreco/trainval.py", line 64, in train_step
    res_combined = self.forward(data_blob)
  File "/afs/slac.stanford.edu/u/nu/kterao/sw/lartpc_mlreco3d/mlreco/trainval.py", line 81, in forward
    res = self._forward(blob)
  File "/afs/slac.stanford.edu/u/nu/kterao/sw/lartpc_mlreco3d/mlreco/trainval.py", line 120, in _forward
    segmentation = self._net(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
```
This is produced by modifying `test_uresnet_ppn.cfg` where `gpus: "1,3"`

.
